#!/bin/bash
DIR=`dirname $0`
export PYTHONPATH=${DIR}:${DIR}/lib:${DIR}/plugins
if [ .$PYTHON = . ]; then
	PYTHON=python
fi
${PYTHON} ${DIR}/bCNC.py $*
#python -m cProfile -o bCNC.out ${DIR}/bCNC.py $*
