#!/usr/bin/env sh

DIR=`dirname $0`
PYTHONPATH=${DIR}:${DIR}/lib:${DIR}/plugins
export DIR PYTHONPATH
if [ .$PYTHON = . ]; then
	PYTHON=python
fi
${PYTHON} ${DIR}/bCNC.py $*
#python -m cProfile -o bCNC.out ${DIR}/bCNC.py $*
